"""LACE-Multi and f-Multi loss variants.

Implements the two loss functions from the "original three improvements" of
``documents/LACE改进方案深度理论分析.md`` against which the MBA family is
compared:

- ``LACEMulti`` (registry name ``lace_multi``): multiplicative modulation of
  cross-entropy, Chapter 1.
- ``FMulti`` (registry name ``f_multi``): multiplicative modulation of the
  alpha-divergence loss (Roulet et al., ICML 2025), Chapter 2.

Both losses carry a per-class learnable parameter ``eps`` of shape ``(C,)``
(initialised to 0, so ``sigma(eps) = 0.5`` initially) that controls the
strength of the hard-sample amplification factor.

Reference: V. Roulet, T. Liu, N. Vieillard, M. E. Sander, M. Blondel.
"Loss Functions and Operators Generated by f-Divergences." ICML 2025.
arXiv:2501.18537.
"""

from __future__ import annotations

import math

import torch
import torch.nn as nn
import torch.nn.functional as F


class LACEMulti(nn.Module):
    r"""Multiplicative-modulation cross-entropy loss (Chapter 1).

    .. math::
        L_{\text{LACE-Multi}}
            = \left[1 + \sigma(\epsilon_y)\,(1 - P_t)\right]\,(-\ln P_t)

    where :math:`P_t = \mathrm{softmax}(z)_y` is the predicted probability of
    the correct class and :math:`\epsilon_y` is a per-class learnable
    parameter.  Gradients flow through both ``eps`` (via the sigmoid) and the
    ``logits`` (via the softmax).

    Verified properties:
      * ``sigma(eps) -> 0``  =>  :math:`L \to L_{CE}`  (recovers cross-entropy).
      * ``P_t -> 1``        =>  :math:`L \to 0`       (easy/correct samples vanish).
      * ``P_t -> 0``        =>  :math:`L \to \infty`   (hard samples amplified).
    """

    def __init__(self, num_classes: int, eps_init: float = 0.0) -> None:
        super().__init__()
        self.num_classes = num_classes
        # Per-class learnable parameter; sigma(0) = 0.5.
        self.eps = nn.Parameter(torch.full((num_classes,), float(eps_init)))

    def forward(self, logits: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
        log_probs = F.log_softmax(logits, dim=-1)                       # (B, C)
        log_pt = log_probs.gather(1, targets.view(-1, 1)).squeeze(1)    # (B,)
        pt = log_pt.exp()                                               # P_t, (B,)
        sigma_eps = torch.sigmoid(self.eps[targets])                    # (B,)
        l_ce = -log_pt                                                  # L_CE, (B,)
        loss = (1.0 + sigma_eps * (1.0 - pt)) * l_ce                    # (B,)
        return loss.mean()


class FMulti(nn.Module):
    r"""Multiplicative-modulation alpha-divergence loss (Chapter 2).

    .. math::
        L_{\text{f-Multi}}
            = \left[1 + \sigma(\epsilon_y)\,(1 - P_t^{\alpha})\right]\,
               (-\ln P_t^{\alpha})

    where :math:`P_t^{\alpha} = \mathrm{softmax}((1-\alpha)\,\mathbf z)_y` is the
    f-softargmax probability of the correct class and :math:`L_\alpha = -\ln
    P_t^{\alpha}` is the target-dependent Fenchel-Young NLL loss (Roulet et al.,
    ICML 2025, Eq. 5).

    f-softargmax (tempered softmax, closed form for uniform reference)::

        p*_j = softmax(z_j * (1 - alpha))_j

    Degeneration: ``alpha = 0`` -> standard softmax + CE, so f-Multi degenerates
    to LACE-Multi.  ``alpha = 1`` -> uniform softmax (degenerate); falls back to
    ``KL(uniform || p)``.

    Note: an earlier implementation used the f-divergence regulariser
    ``D_f(p, uniform)`` (Roulet et al., Eq. 8) as ``L_alpha``.  That form is
    target-independent and minimised (= 0) at the uniform distribution,
    causing the model to collapse to random-chance accuracy.  The NLL form
    used here is the correct target-dependent classification loss.
    """

    def __init__(
        self, num_classes: int, alpha: float = 0.5, eps_init: float = 0.0
    ) -> None:
        super().__init__()
        self.num_classes = num_classes
        self.alpha = float(alpha)
        # Per-class learnable parameter; sigma(0) = 0.5.
        self.eps = nn.Parameter(torch.full((num_classes,), float(eps_init)))

    def f_softmax(self, logits: torch.Tensor) -> torch.Tensor:
        """f-softargmax for the alpha-divergence with uniform reference.

        Closed form: ``p* = softmax(z * (1 - alpha))``.
        ``alpha = 0`` -> standard softmax; ``alpha = 1`` -> degenerate (uniform).
        """
        return F.softmax(logits * (1.0 - self.alpha), dim=-1)

    def alpha_div_loss(
        self, logits: torch.Tensor, targets: torch.Tensor
    ) -> torch.Tensor:
        """Per-sample alpha-divergence loss ``(B,)``.

        Uses the target-dependent Fenchel-Young NLL form
        ``L_alpha = -ln P_t^alpha`` where ``P_t^alpha = softmax((1-alpha)*z)_y``.
        This is the proper classification loss (Roulet et al., Eq. 5), NOT the
        target-independent f-divergence regulariser (their Eq. 8), which is
        minimised at the uniform distribution and collapses training.
        """
        alpha = self.alpha

        if abs(alpha - 1.0) < 1e-6:
            # alpha -> 1: scale = 0, softmax(0) = uniform, NLL = log C (constant).
            # Fall back to KL(uniform || p) for a non-trivial alpha=1 loss.
            p = F.softmax(logits, dim=-1)
            p_safe = torch.where(p > 0, p, p.new_tensor(1e-12))
            c = float(self.num_classes)
            log_p_sum = torch.log(p_safe).sum(dim=-1)           # (B,)
            return -math.log(c) - log_p_sum / c                  # (B,)

        # General case (alpha not in {1}): NLL of the f-softargmax probability.
        # For alpha = 0 this degenerates to standard cross-entropy.
        scale = 1.0 - alpha
        log_pt_alpha = F.log_softmax(scale * logits, dim=-1).gather(
            1, targets.view(-1, 1)
        ).squeeze(1)                                            # (B,)
        return -log_pt_alpha                                    # (B,)

    def forward(self, logits: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
        p_star = self.f_softmax(logits)                                 # (B, C)
        p_star_t = p_star.gather(1, targets.view(-1, 1)).squeeze(1)    # P_t^alpha, (B,)
        sigma_eps = torch.sigmoid(self.eps[targets])                    # (B,)
        l_alpha = self.alpha_div_loss(logits, targets)                  # (B,)
        loss = (1.0 + sigma_eps * (1.0 - p_star_t)) * l_alpha           # (B,)
        return loss.mean()
